site_name: Documentation - Alireza Mohajer
site_url: https://alirzw-mhjr.github.io/ITMO_ICT_WebDevelopment_tools_2025-2026/
repo_url: https://github.com/alirzw-mhjr/ITMO_ICT_WebDevelopment_tools_2025-2026
repo_name: GitHub Repository
docs_dir: docs

nav:
  - Главная: index.md
  - Лабораторные работы:
      - Лабораторная работа 1: laboratory_works/laboratory_work_1.md
      - Лабораторная работа 2: laboratory_works/laboratory_work_2.md
      - Лабораторная работа 3: laboratory_works/laboratory_work_3.md

theme:
  name: material
  language: ru
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
