"""update user model and relationships

Revision ID: e5b07764b6a7
Revises: ef146e731a53
Create Date: 2026-04-18 21:44:56.225199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b07764b6a7'
down_revision: Union[str, Sequence[str], None] = 'ef146e731a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_genres', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('book_genres', 'book_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('book_genres', 'genre_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('books', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('exchanges', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('exchanges', 'requester_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('exchanges', 'owner_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('exchanges', 'requested_userbook_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('exchanges', 'offered_userbook_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('genres', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'exchange_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_books', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_books', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_books', 'book_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_books', 'book_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_books', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_books', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('messages', 'exchange_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('genres', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('exchanges', 'offered_userbook_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchanges', 'requested_userbook_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchanges', 'owner_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchanges', 'requester_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchanges', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('books', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('book_genres', 'genre_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('book_genres', 'book_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('book_genres', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
